stages:
  - regression_BE

regression_BE:
  stage: regression_BE
  image: python:3.10
  before_script:
    -pip3 install -r ./requirements.txt
  script:
  - echo "Running tests...  "
  - python3 -m pytest -m tcid61

