export DB_USER=vickie
export DB_PASSWORD=AutomationIsGreat
export DB_PORT_OVERRIDE=3309
export DB_HOST_OVERRIDE=bootcamp.store.supersqa.com
export DB_DATABASE_OVERRIDE=bootcampstore
export DB_TABLE_PREFIX_OVERRIDE=wp_